### ISSUE TITLE
parse-ger.sh : NegativeArraySizeException

### ISSUE THREAD

**Issue by SabineKoban** [microth/mateplus#2]
Hi Mircoth,

for my Master-Thesis I'm working with the Mate-Tools Parser. I found your mateplus on github. Because I'm working with German texts I need to get the German version run. As you recommended in the README.md I downloaded the models and the libraries and put them in the provided folders /lib and /models. Within the bash script parse-ger.sh it looks like the following:

 please download these models and adjust their locations accordingly 
LEMMA_MODEL=models/lemma-ger.model 
PARSER_MODEL=models/parse-ger.model # Bernd's joint tagging/parsing model 
TOKEN_MODEL=models/de-token.bin # German tokenization model for OpenNLP SRL_MODEL=models/srl-EMNLP14+fs-ger.model # German mateplus SRL model, trained on joint tagger/parser output 
RERANKER="-reranker" 
TOKENIZE="-tokenize -token $TOKEN_MODEL" 
# JAVA=/usr/lib/jvm/java-1.8.0/bin/java

JAVA=/usr/lib/jvm/java-8-openjdk-amd64/bin/java 
# parse $1

$JAVA -cp "lib/opennlp-maxent-3.0.3.jar:lib/opennlp-tools-1.5.3.jar:lib/liblinear-1.51-with-deps.jar:lib/stanford-corenlp-3.6.0.jar:lib/transition-1.30.jar:lib/whatswrong-0.2.3.jar:mateplus.jar" -Xmx6g se.lth.cs.srl.CompletePipeline ger -lemma $LEMMA_MODEL -parser $PARSER_MODEL  -hybrid -srl models/srl-EMNLP14+fs-ger.model $RERANKER $TOKENIZE -test $1

When try to run the script on the command shell with ./scripts/parse-ger.sh testfile.txt I get a NegativeArraySizeException

51.23.374 is2.data.ParametersFloat 142:read
→ read parameters 50000000 not zero 840044
51.23.380 is2.data.Cluster 111:<init>
→ Read cluster with 0 words
51.23.380 is.lemmatizer.Lemmatizer 185:readModel
→ Loading data finished
51.23.381 is.lemmatizer.Lemmatizer 187:readModel
→ number of params 50000000
51.23.381 is.lemmatizer.Lemmatizer 188:readModel
→ number of classes 336
51.23.388 is.transition2a.Parser 720:readModel
→ reading data started
51.23.773 is.data.Cluster 111:<init> 
→ Read cluster with 0 words

Java.lang.NegativeArraySizeException
    at is2.transition2a.Lexicon.read(Lexicon.java.282)
    at is2.transition2a.Parser.readModel(Parser.java:730)
    at is2.transition2a.Parser.<init>(Parser.java:112)
    at is2.transition2a.Parser.<init>(Parser.java:146)
    at se.lth.cs.srl.preprocessor.HybridPreprocessor.<init>(HybridPreprocessor.java:21)
    at se.lth.cs.srl.languages.Language.getPreprocessor(Language.java:84)
    at se.lth.cs.srl.CompletePipeline.getCompletePipeline(CompletePipeline.java:68)
    at se.lth.cs.srl.CompletePipeline.main(CompletePipeline.java:146)

I have no idea how and where to fix that problem. I got totally stuck. Can you help me, please?
Thanks in advance and have a nice evening,
Sabine

**Comment by mujdricza** [comment]
Hi Sabine,

I am Eva - and just had the same problem.

For me, another parser is working:
PARSER_MODEL=$PATH_TO_MODELS/pet-ger-S2a-40-0.25-0.1-2-2-ht4-hm4-kk0

This is the download "German Models / Download of Joint-Parsing-Model: parser+tagger+morphology" on this page: https://code.google.com/archive/p/mate-tools/wikis/ParserAndModels.wiki

Thus, I cannot tell you the reason, but I hope the answer helps (but maybe too late...).

(Probably not relevant for you, but I just mention it for log purposes: The input testfile.txt should not entail any empty line.)

Best regards,
Eva
