### ISSUE TITLE
java 

### ISSUE THREAD

**Issue by krithikakm** [microth/mateplus#3]
Hello, 

I am getting an error while running parse.sh and parse-framenet.sh:
" /usr/lib/jvm/java-1.8.0/bin/java: No such file or directory "
I installed Java SE Development Kit 8u111. Are there any particular settings to be changed in the shell script or additional softwares that I need download and update my system?
I have used the online application. But I would like to run it as a standalone application to retrieve the base form of words.

Thanks,
Krithika

**Comment by microth** [comment]
No, just edit the file parse.sh and parse-framenet.sh to make sure the variable JAVA points to the right command for java on your system (e.g. just "java").
